version: "3.7"
services:
  db:
    container_name: strava_db
    image: postgres:13.5
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-database:/var/lib/postgresql/data/pgdata:rw,Z
  web:
    container_name: strava_web
    build: .
    depends_on:
      - db
    env_file: .env.dev
    command: >
      sh -c "/app/scripts/run_app_dev.sh"
    volumes:
      - .:/app:rw,Z
    ports:
      - "8000:8000"
#  redis:
#    container_name: redis
#    image: redis:alpine
#
#  celery:
#    container_name: celery
#    restart: always
#    build:
#      context: .
#    command: celery -A pharmafootpath worker -l debug
#    volumes:
#      - ./:/app
#      - ./trial_downloads:/app/trial_downloads:rw,Z
#      - ./parallel_trade_downloads:/app/parallel_trade_downloads:rw,Z
#    env_file: .env.develop
#    depends_on:
#      - db
#      - redis
##      - web
#  celery-beat:
#    container_name: celery-beat
#    restart: always
#    build:
#      context: .
#    command: celery -A pharmafootpath beat -l debug
#    volumes:
#      - ./:/app
#      - ./trial_downloads:/app/trial_downloads:rw,Z
#      - ./parallel_trade_downloads:/app/parallel_trade_downloads:rw,Z
#    env_file: .env.develop
#    depends_on:
#      - db
#      - redis
##      - web


volumes:
  db-database: