version: "3.7"
services:
  db:
    container_name: strava_db
    image: postgres:13.5
    ports:
      - "5434:5432"
    env_file: .env.dev
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-database:/var/lib/postgresql/data/pgdata:rw,Z

  redis:
    container_name: redis
    image: redis:alpine

  backend:
    container_name: strava_backend
    build: .
    depends_on:
      - db
      - redis
    links:
      - redis
      - celery
    env_file: .env.dev
    command: >
      sh -c "sleep 10 && /app/scripts/run_app_dev.sh"  # Добавляем задержку для ожидания запуска db и redis
    volumes:
      - .:/app:rw,Z
    ports:
      - "8000:8000"

  celery:
    container_name: celery
    env_file: .env.dev0
    restart: always
    build: .
    command: >
      sh -c "sleep 10 && celery -A strava_views worker --loglevel=info"  # Задержка для ожидания backend, db, redis
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app
    links:  # Убираем links между celery и backend, чтобы избежать циклической зависимости
      - redis

volumes:
  db-database:
