version: "3.7"
services:

  redis:
    container_name: redis
    image: redis:alpine

  backend:
    container_name: strava_backend
    image: rvksoft/strava_templates_backend:latest
    depends_on:
      - redis
    links:
      - redis
      - celery
    env_file: .env
    command: >
      sh -c "sleep 10 && /app/scripts/run_app_dev.sh"
    volumes:
      - .:/app:rw,Z
    ports:
      - "8000:8000"

  web:
    image: rvksoft/strava_templates_web:latest
    ports:
      - "3000:80"

  celery:
    container_name: celery
    image: rvksoft/strava_templates_celery:latest
    env_file: .env
    restart: always
    command: >
      sh -c "sleep 10 && celery -A strava_views worker --loglevel=info"
    depends_on:
      - redis
    volumes:
      - ./:/app
    links:
      - redis
