# Generated by Django 5.0.6 on 2024-07-18 16:51

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('resource_state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('summary_polyline', models.TextField()),
                ('resource_state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_state', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('distance', models.FloatField()),
                ('moving_time', models.IntegerField()),
                ('elapsed_time', models.IntegerField()),
                ('total_elevation_gain', models.FloatField()),
                ('type', models.CharField(max_length=50)),
                ('sport_type', models.CharField(max_length=50)),
                ('workout_type', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('start_date_local', models.DateTimeField()),
                ('timezone', models.CharField(max_length=50)),
                ('utc_offset', models.FloatField()),
                ('location_city', models.CharField(blank=True, max_length=255, null=True)),
                ('location_state', models.CharField(blank=True, max_length=255, null=True)),
                ('location_country', models.CharField(max_length=255)),
                ('achievement_count', models.IntegerField()),
                ('kudos_count', models.IntegerField()),
                ('comment_count', models.IntegerField()),
                ('athlete_count', models.IntegerField()),
                ('photo_count', models.IntegerField()),
                ('trainer', models.BooleanField()),
                ('commute', models.BooleanField()),
                ('manual', models.BooleanField()),
                ('private', models.BooleanField()),
                ('visibility', models.CharField(max_length=50)),
                ('flagged', models.BooleanField()),
                ('gear_id', models.CharField(blank=True, max_length=255, null=True)),
                ('start_latlng', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2)),
                ('end_latlng', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2)),
                ('average_speed', models.FloatField()),
                ('max_speed', models.FloatField()),
                ('average_watts', models.FloatField()),
                ('kilojoules', models.FloatField()),
                ('device_watts', models.BooleanField()),
                ('has_heartrate', models.BooleanField()),
                ('heartrate_opt_out', models.BooleanField()),
                ('display_hide_heartrate_option', models.BooleanField()),
                ('elev_high', models.FloatField()),
                ('elev_low', models.FloatField()),
                ('upload_id', models.BigIntegerField()),
                ('upload_id_str', models.CharField(max_length=255)),
                ('external_id', models.CharField(max_length=255)),
                ('from_accepted_tag', models.BooleanField()),
                ('pr_count', models.IntegerField()),
                ('total_photo_count', models.IntegerField()),
                ('has_kudoed', models.BooleanField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.athlete')),
                ('map', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activities.map')),
            ],
        ),
        migrations.CreateModel(
            name='SyncingActivitiesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=20)),
                ('page', models.IntegerField()),
                ('per_page', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
