# Generated by Django 5.0.6 on 2024-10-13 05:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_state', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('moving_time', models.IntegerField(blank=True, null=True)),
                ('elapsed_time', models.IntegerField(blank=True, null=True)),
                ('total_elevation_gain', models.FloatField(blank=True, null=True)),
                ('sport_type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('workout_type', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('start_date_local', models.DateTimeField()),
                ('timezone', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('utc_offset', models.IntegerField(blank=True, null=True)),
                ('location_city', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('location_state', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('location_country', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('achievement_count', models.IntegerField(blank=True, null=True)),
                ('kudos_count', models.IntegerField(blank=True, null=True)),
                ('comment_count', models.IntegerField(blank=True, null=True)),
                ('athlete_count', models.IntegerField(blank=True, null=True)),
                ('photo_count', models.IntegerField(blank=True, null=True)),
                ('trainer', models.BooleanField(blank=True, default=None, null=True)),
                ('commute', models.BooleanField(blank=True, default=None, null=True)),
                ('manual', models.BooleanField(blank=True, default=None, null=True)),
                ('private', models.BooleanField(blank=True, default=None, null=True)),
                ('visibility', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('flagged', models.BooleanField(blank=True, default=None, null=True)),
                ('gear_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('start_latlng', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=2)),
                ('end_latlng', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=2)),
                ('average_speed', models.IntegerField(blank=True, null=True)),
                ('max_speed', models.FloatField(blank=True, null=True)),
                ('average_watts', models.IntegerField(blank=True, null=True)),
                ('kilojoules', models.IntegerField(blank=True, null=True)),
                ('device_watts', models.BooleanField(blank=True, default=None, null=True)),
                ('has_heartrate', models.BooleanField(blank=True, default=None, null=True)),
                ('heartrate_opt_out', models.BooleanField(blank=True, default=None, null=True)),
                ('display_hide_heartrate_option', models.BooleanField(blank=True, default=None, null=True)),
                ('elev_high', models.FloatField(blank=True, null=True)),
                ('elev_low', models.FloatField(blank=True, null=True)),
                ('upload_id', models.CharField(blank=True, null=True)),
                ('upload_id_str', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('external_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('from_accepted_tag', models.BooleanField(blank=True, default=None, null=True)),
                ('pr_count', models.IntegerField(blank=True, null=True)),
                ('total_photo_count', models.IntegerField(blank=True, null=True)),
                ('has_kudoed', models.BooleanField(blank=True, default=None, null=True)),
                ('average_temp', models.FloatField(blank=True, default=None, null=True)),
                ('average_heartrate', models.IntegerField(blank=True, null=True)),
                ('max_heartrate', models.FloatField(blank=True, null=True)),
                ('average_cadence', models.FloatField(blank=True, null=True)),
                ('max_watts', models.IntegerField(blank=True, null=True)),
                ('weighted_average_watts', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('summary_polyline', models.TextField()),
                ('resource_state', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
