# Generated by Django 5.0.6 on 2024-08-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_map_stravaprofile_status_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravaprofile',
            name='page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stravaprofile',
            name='per_page',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
