# Generated by Django 5.0.6 on 2024-07-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_average_heartrate_activity_average_temp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='average_heartrate',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='activity',
            name='average_temp',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='activity',
            name='max_heartrate',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
