# Generated by Django 5.0.6 on 2024-08-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_stravaprofile_page_stravaprofile_per_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravaprofile',
            name='page',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='stravaprofile',
            name='per_page',
            field=models.IntegerField(blank=True, default=200, null=True),
        ),
    ]
