# Generated by Django 5.0.6 on 2024-07-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_activity_average_heartrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='average_temp',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
