# Generated by Django 5.0.6 on 2024-08-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_stravaprofile_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravaprofile',
            name='onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
