# Generated by Django 5.0.6 on 2024-07-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_alter_activity_average_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='average_heartrate',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='average_temp',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='max_heartrate',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
