# Generated by Django 5.0.6 on 2024-07-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_alter_activity_distance_alter_activity_elev_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='average_cadence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
