# Generated by Django 5.0.6 on 2024-07-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_activity_average_cadence'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='max_watts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
