# Generated by Django 5.0.6 on 2024-07-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_activity_max_watts'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='weighted_average_watts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
