# Generated by Django 5.0.6 on 2024-10-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stravauserprofile',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='stravauserprofile',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='stravauserprofile',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='stravauserprofile',
            name='strava_id',
        ),
    ]
