# Generated by Django 5.0.6 on 2024-10-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_stravauserprofile_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravauserprofile',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stravauserprofile',
            name='expires_at',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stravauserprofile',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stravauserprofile',
            name='strava_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
