# Generated by Django 5.0.6 on 2024-11-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_stravauserprofile_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravauserprofile',
            name='page',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='stravauserprofile',
            name='per_page',
            field=models.IntegerField(blank=True, default=200, null=True),
        ),
        migrations.AddField(
            model_name='stravauserprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default=None, max_length=20, null=True),
        ),
    ]
