# Generated by Django 5.0.6 on 2024-11-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_stravauserprofile_page_stravauserprofile_per_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravauserprofile',
            name='expires_in',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
