name: Deploy App to EC2

on:
  workflow_dispatch:
    inputs:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Get EC2 instance IP
        id: get_instance_ip
        run: |
          INSTANCE_IP=$(aws cloudformation describe-stacks \
            --stack-name StravaTemplatesStack \
            --query "Stacks[0].Outputs[?OutputKey=='PublicIP'].OutputValue" \
            --output text)
          echo "INSTANCE_IP=$INSTANCE_IP" >> $GITHUB_ENV

      - name: Add EC2 Host to known_hosts
        run: ssh-keyscan -H "${{ env.INSTANCE_IP }}" >> ~/.ssh/known_hosts

      - name: Connect to EC2 instance and pull Docker image
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.INSTANCE_IP }} << 'EOF'
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

            docker pull rvksoft/strava_templates_backend:latest
            docker pull rvksoft/strava_templates_web:latest

            docker stop strava_templates_web strava_templates_backend || true
            docker rm strava_templates_web strava_templates_backend || true
          
            docker run -d --name strava_templates_backend rvksoft/strava_templates_backend:latest
            docker run -d --name strava_templates_web rvksoft/strava_templates_web:latest
          EOF
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}