name: Build and Push Docker image

on:
  workflow_dispatch:
    inputs:
      apiUrl:
        description: 'API URL'
        required: true
        default: 'http://qwqweqwe.cloud'
        type: string

      tag:
        description: 'Docker image tag'
        required: true
        default: 'latest'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build backend Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/strava_templates_backend:${{ github.event.inputs.tag }} -f backend/Dockerfile backend/

    - name: Push backend Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/strava_templates_backend:${{ github.event.inputs.tag }}

    - name: Build frontend Docker image
      run: |
        docker build --build-arg BACKEND_API_URL=${{ github.event.inputs.apiUrl }} -t ${{ secrets.DOCKER_USERNAME }}/strava_templates_web:${{ github.event.inputs.tag }} -f web/Dockerfile web/

    - name: Push frontend Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/strava_templates_web:${{ github.event.inputs.tag }}
